#!/usr/bin/env node
/**
 * generate-seo.mjs — DEPRECATED as a generator.
 *
 * sitemap.xml, robots.txt, llms.txt and llms-full.txt are now generated by the
 * client prerenderer (client/scripts/prerender.mjs) at the end of every client
 * build, straight from src/data/recipes.json — the same file the pages render.
 * That keeps the sitemap and the prerendered HTML unable to disagree.
 *
 * This script is kept so `npm run seo:build` still works in CI/docs: it simply
 * verifies the data builds and reminds you to run the client build.
 */
import { execSync } from 'node:child_process';

try {
  execSync('node scripts/resolve-nutrition.mjs', { stdio: 'inherit' });
  console.log(
    '\nseo:build note: sitemap.xml / robots.txt / llms.txt / llms-full.txt are emitted\n' +
      'by the client prerenderer into client/dist/. Run `npm --prefix client run build`\n' +
      'to (re)generate them.'
  );
} catch {
  process.exit(1);
}
